  - name: install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: enable nginx 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes 
         
  - name: run app pre-requisites
    ansible.builtin.import_role:
      name: common
      tasks_from: app-pre-req

  - name: copy backend service
    ansible.builtin.template:
      src: expense.conf.j2
      dest: /etc/nginx/default.d/expense.conf
    notify: 
    - restart nginx

  # if there is any change in configuration only, we need to restart the server,now everywhere there is a change
  # so we need to restart everytime
  # - name: restart nginx
  #   ansible.builtin.service:
  #     name: nginx
  #     state: restarted          
